name = "jasonliao-site"
compatibility_date = "2026-04-04"
pages_build_output_dir = "."

[[d1_databases]]
binding = "CMS_DB"
database_name = "jasonliao-cms"
database_id = "9754b1b1-a382-45cb-b1aa-d55bbf6f0f9c"
